### ISSUE TITLE
Figure out swipeState setting inconsistency

### ISSUE THREAD

**Issue by kyleve** [kyleve/Listable#139]
@kylebshr: One question I have is that I'm surprised this setter method and the property's didSet are different:

```
        private var swipeState: SwipeActionState = .closed {
            didSet {
                if oldValue != swipeState {
                    swipeConfiguration?.swipeView.apply(state: swipeState)
                }
            }
        }
```

Based on UIKit paradigm, I'd simply expect the `didSet` to call through to a `set(state: newValue, animated:false)`. If the behaviour is meant to be meaningfully different, should the name of this method be different?

_Originally posted by @kyleve in https://github.com/kyleve/Listable/pull/136_

**Comment by kylebshr** [comment]
Crap, forgot to look at this today. I’m on a walk rn but will take a look tonight

**Comment by kylebshr** [comment]
The behavior _is_ pretty much the same, since the function sets the property which triggers the `didSet`. I'm not actually sure how the setter could just call the function, since the function sets state - it would be recursive. If the function didn't need to store the state, it could work that way, but since it needs to store the value I think that's why it's set up how it is?
